package dev.sqlcj.generator;

import dev.sqlcj.analysis.QueryColumn;
import dev.sqlcj.analysis.QueryModel;
import dev.sqlcj.analysis.QueryParameter;
import dev.sqlcj.parser.QueryType;
import dev.sqlcj.type.DefaultTypeResolver;
import dev.sqlcj.type.TypeResolver;

import java.nio.file.Path;
import java.util.stream.Collectors;

public final class JavaCodeGenerator implements CodeGenerator {

    private final TypeResolver typeResolver = new DefaultTypeResolver();

    @Override
    public GeneratedFile generate(QueryModel query) {
        return new GeneratedFile(
                buildPath(query),
                generateSource(query)
        );
    }

    private Path buildPath(QueryModel query) {
        return Path.of("generated", query.name() + ".java");
    }

    private String generateSource(QueryModel query) {
        return """
                %s

                %s

                %s
                
                %s
                """.formatted(
                generatePackage(),
                generateImports(query),
                generateJavaDoc(query),
                generateClass(query)
        );
    }

    private String generatePackage() {
        return "package generated;";
    }

    private String generateImports(QueryModel query) {
        if (query.type() == QueryType.MANY) {
            return "import java.util.List;";
        }

        return "";
    }

    private String generateJavaDoc(QueryModel query) {
        return """
        /**
         * Generated by sqlcj.
         *
         * Query: %s
         * Table: %s
         * Type: %s
         */
        """.formatted(
                query.name(),
                query.table(),
                query.type()
        );
    }

    private String generateClass(QueryModel query) {
        return """
                public final class %s {

                %s
                
                %s
                }
                """.formatted(
                query.name(),
                indent(generateResultType(query)),
                indent(generateMethod(query))
        );
    }

    private String indent(String text) {
        return text.indent(4).stripTrailing();
    }

    private String generateResultType(QueryModel query) {
        return """
                public record Result(
                %s
                ) {
                }
                """.formatted(
                generateResultComponents(query)
        );
    }

    private String generateResultComponents(QueryModel query) {
        return query.columns().stream()
                .map(this::generateResultComponent)
                .collect(Collectors.joining(",\n"));
    }

    private String generateResultComponent(QueryColumn column) {
        return "%s %s".formatted(
                typeResolver.resolve(column.type()),
                column.name()
        ).indent(4).stripTrailing();
    }

    private String generateMethodParameters(QueryModel query) {
        return query.parameters().stream()
                .map(this::generateMethodParameter)
                .collect(Collectors.joining(", "));
    }

    private String generateMethodParameter(QueryParameter parameter) {
        String type = typeResolver.resolve(parameter.type());

        return type + " param" + parameter.index();
    }

    private String generateMethod(QueryModel query) {
        return """
        public %s %s(%s) {
        }
        """.formatted(
                generateReturnType(query),
                generateMethodName(query),
                generateMethodParameters(query)
        );
    }

    private String generateMethodName(QueryModel query) {
        return Character.toLowerCase(query.name().charAt(0)) + query.name().substring(1);
    }

    private String generateReturnType(QueryModel query) {
        return switch (query.type()) {
            case ONE -> "Result";
            case MANY -> "List<Result>";
            case EXEC -> "void";
            case EXEC_RESULT -> "void";
            case BATCH_EXEC -> "void";
            case BATCH_MANY -> "void";
            case BATCH_ONE -> "void";
        };
    }
}
