package dev.sqlcj.generator;

import dev.sqlcj.analysis.QueryModel;

import java.nio.file.Path;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

public final class JavaCodeGenerator implements CodeGenerator {

    @Override
    public GeneratedFile generate(QueryModel query) {
        return new GeneratedFile(
                buildPath(query),
                generateSource(query)
        );
    }

    private Path buildPath(QueryModel query) {
        return Path.of("generated", query.name() + ".java");
    }

    private String generateSource(QueryModel query) {
        return """
            %s

            %s

            %s
            """.formatted(
                generatePackage(),
                generateJavaDoc(query),
                generateClass(query)
        );
    }

    private String generatePackage() {
        return "package generated;";
    }

    private String generateJavaDoc(QueryModel query) {
        return """
        /**
         * Generated by sqlcj.
         *
         * Query: %s
         * Table: %s
         * Type: %s
         */
        """.formatted(
                query.name(),
                query.table(),
                query.type()
        );
    }

    private String generateClass(QueryModel query) {
        return """
        public final class %s {

        %s
        }
        """.formatted(
                query.name(),
                indent(generateMethod(query))
        );
    }

    private String indent(String text) {
        return text.indent(4).stripTrailing();
    }

    private String generateMethodParameters(QueryModel query) {
        return IntStream.rangeClosed(1, query.parameters().size())
                .mapToObj(i -> "Object param" + i)
                .collect(Collectors.joining(", "));
    }

    private String generateMethod(QueryModel query) {
        return """
        public %s %s(%s) {
        }
        """.formatted(
                generateReturnType(query),
                generateMethodName(query),
                generateMethodParameters(query)
        );
    }

    private String generateMethodName(QueryModel query) {
        return Character.toLowerCase(query.name().charAt(0)) + query.name().substring(1);
    }

    private String generateReturnType(QueryModel query) {
        return switch (query.type()) {
            case ONE, MANY -> "Object";
            case EXEC -> "void";
            case EXEC_RESULT -> "void";
            case BATCH_EXEC -> "void";
            case BATCH_MANY -> "void";
            case BATCH_ONE -> "void";
        };
    }
}
