package dev.sqlcj.generator;

import dev.sqlcj.analysis.QueryColumn;
import dev.sqlcj.analysis.QueryModel;
import dev.sqlcj.analysis.QueryParameter;
import dev.sqlcj.parser.QueryType;
import dev.sqlcj.schema.ColumnType;
import dev.sqlcj.type.DefaultTypeResolver;
import dev.sqlcj.type.TypeResolver;

import java.nio.file.Path;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

public final class JavaCodeGenerator implements CodeGenerator {

    private static final String DEFAULT_PACKAGE = "generated";

    private final TypeResolver typeResolver = new DefaultTypeResolver();
    private final String packageName;

    public JavaCodeGenerator() {
        this(DEFAULT_PACKAGE);
    }

    public JavaCodeGenerator(String packageName) {
        this.packageName = packageName;
    }

    @Override
    public GeneratedFile generate(QueryModel query) {
        return new GeneratedFile(
            buildPath(query),
            generateSource(query)
        );
    }

    private Path buildPath(QueryModel query) {
        return packageDirectory().resolve(query.name() + ".java");
    }

    private Path packageDirectory() {
        String[] segments = packageName.split("\\.");

        return Path.of(
            segments[0],
            Arrays.copyOfRange(segments, 1, segments.length)
        );
    }

    private String generateSource(QueryModel query) {
        return """
            %s

            %s

            %s

            %s
            """
            .formatted(
                generatePackage(),
                generateImports(query),
                generateJavaDoc(query),
                generateClass(query)
            );
    }

    private String generatePackage() {
        return "package " + packageName + ";";
    }

    private String generateImports(QueryModel query) {
        Set<String> imports = new LinkedHashSet<>();

        imports.add("dev.sqlcj.runtime.QueryExecutor");

        if (hasResult(query)) {
            imports.add("dev.sqlcj.runtime.RowMapper");
            imports.add("java.util.List");
        }

        query.columns().stream()
            .map(QueryColumn::type)
            .map(this::resolveImport)
            .filter(Objects::nonNull)
            .forEach(imports::add);

        query.parameters().stream()
            .map(QueryParameter::type)
            .map(this::resolveImport)
            .filter(Objects::nonNull)
            .forEach(imports::add);

        return imports.stream()
            .map(type -> "import " + type + ";")
            .collect(Collectors.joining("\n"));
    }

    private boolean hasResult(QueryModel query) {
        return query.type() == QueryType.ONE
            || query.type() == QueryType.MANY;
    }

    private String resolveImport(ColumnType type) {
        return switch (type) {
            case DATE -> "java.time.LocalDate";
            case TIMESTAMP -> "java.time.LocalDateTime";
            case DECIMAL -> "java.math.BigDecimal";
            default -> null;
        };
    }

    private String generateJavaDoc(QueryModel query) {
        return """
            /**
             * Generated by sqlcj.
             *
             * Query: %s
             * Table: %s
             * Type: %s
             */
            """
            .formatted(
                query.name(),
                query.table(),
                query.type()
            );
    }

    private String generateClass(QueryModel query) {
        String rowMapper = hasResult(query)
            ? indent(generateRowMapper(query))
            : "";

        return """
            public final class %s {

            %s

            %s

            %s

            %s

            %s
            }
            """
            .formatted(
                query.name(),
                indent(generateExecutorField()),
                indent(generateConstructor(query)),
                indent(generateResultType(query)),
                rowMapper,
                indent(generateMethod(query))
            );
    }

    private String indent(String text) {
        return text.indent(4).stripTrailing();
    }

    private String generateResultType(QueryModel query) {
        return """
            public record %s(
            %s
            ) {
            }
            """
            .formatted(
                generateResultTypeName(query),
                generateResultComponents(query)
            );
    }

    private String generateResultComponents(QueryModel query) {
        return query.columns().stream()
            .map(this::generateResultComponent)
            .collect(Collectors.joining(",\n"));
    }

    private String generateResultComponent(QueryColumn column) {
        return "%s %s"
            .formatted(
                typeResolver.resolve(column.type()),
                column.name()
            )
            .indent(4)
            .stripTrailing();
    }

    private String generateMethodParameters(QueryModel query) {
        List<String> names = generateParameterNames(query);

        return IntStream.range(0, query.parameters().size())
            .mapToObj(i -> {
                QueryParameter parameter = query.parameters().get(i);

                return typeResolver.resolve(parameter.type())
                    + " "
                    + names.get(i);
            })
            .collect(Collectors.joining(", "));
    }

    private List<String> generateParameterNames(QueryModel query) {
        Map<String, Long> occurrences = query.parameters().stream()
            .collect(
                Collectors.groupingBy(
                    QueryParameter::name,
                    Collectors.counting()
                )
            );

        Map<String, Integer> indexes = new HashMap<>();

        return query.parameters().stream()
            .map(parameter -> {
                String name = parameter.name();

                if (occurrences.get(name) > 1) {
                    int occurrence = indexes.merge(
                        name,
                        1,
                        Integer::sum
                    );

                    name += occurrence;
                }

                return name;
            })
            .toList();
    }

    private String generateMethod(QueryModel query) {
        return switch (query.type()) {
            case ONE, MANY -> generateQueryMethod(query);
            case EXEC, EXEC_RESULT, BATCH_EXEC, BATCH_MANY, BATCH_ONE -> generateUnsupportedMethod(query);
        };
    }

    private String generateQueryMethod(QueryModel query) {
        return """
            public %s %s(%s) {
                return executor.%s(
                        %s,
                        %s,
                        ROW_MAPPER
                );
            }
            """
            .formatted(
                generateReturnType(query),
                generateMethodName(query),
                generateMethodParameters(query),
                generateExecutorMethod(query),
                generateSql(query),
                generateParameterList(query)
            );
    }

    private String generateUnsupportedMethod(QueryModel query) {
        return """
            public %s %s(%s) {
                throw new UnsupportedOperationException("Not implemented");
            }
            """
            .formatted(
                generateReturnType(query),
                generateMethodName(query),
                generateMethodParameters(query)
            );
    }

    private String generateExecutorMethod(QueryModel query) {
        return switch (query.type()) {
            case ONE -> "query";
            case MANY -> "queryMany";
            default -> throw new IllegalStateException(
                "Query type does not produce a result: " + query.type()
            );
        };
    }

    private String generateSql(QueryModel query) {
        return "\"\"\"\n"
            + query.executableSql()
            + "\"\"\"";
    }

    /**
     * Renders the executor arguments in the textual order of the JDBC
     * {@code ?} positions, using the logically ordered method parameter names.
     */
    private String generateParameterList(QueryModel query) {
        Map<Integer, String> namesByIndex = generateParameterNamesByIndex(query);

        return query.bindingParameterIndexes().stream()
            .map(namesByIndex::get)
            .collect(Collectors.joining(", ", "List.of(", ")"));
    }

    private Map<Integer, String> generateParameterNamesByIndex(QueryModel query) {
        List<String> names = generateParameterNames(query);

        Map<Integer, String> namesByIndex = new LinkedHashMap<>();

        for (int i = 0; i < query.parameters().size(); i++) {
            namesByIndex.put(
                query.parameters().get(i).index(),
                names.get(i)
            );
        }

        return namesByIndex;
    }

    private String generateMethodName(QueryModel query) {
        return Character.toLowerCase(query.name().charAt(0)) + query.name().substring(1);
    }

    private String generateReturnType(QueryModel query) {
        return switch (query.type()) {
            case ONE -> generateResultTypeName(query);
            case MANY -> "List<" + generateResultTypeName(query) + ">";
            case EXEC -> "void";
            case EXEC_RESULT -> "void";
            case BATCH_EXEC -> "void";
            case BATCH_MANY -> "void";
            case BATCH_ONE -> "void";
        };
    }

    private String generateResultTypeName(QueryModel query) {
        return query.name() + "Result";
    }

    private String generateRowMapper(QueryModel query) {
        return """
            private static final RowMapper<%s> ROW_MAPPER =
                    resultSet -> new %s(
            %s
            );
            """
            .formatted(
                generateResultTypeName(query),
                generateResultTypeName(query),
                generateResultMappings(query)
            );
    }

    private String generateResultMappings(QueryModel query) {
        return query.columns().stream()
            .map(this::generateResultMapping)
            .collect(Collectors.joining(",\n"));
    }

    private String generateResultMapping(QueryColumn column) {
        String javaType = typeResolver.resolve(column.type());

        return "resultSet.getObject(\"%s\", %s.class)"
            .formatted(
                column.name(),
                javaType
            )
            .indent(8)
            .stripTrailing();
    }

    private String generateExecutorField() {
        return """
            private final QueryExecutor executor;
            """;
    }

    private String generateConstructor(QueryModel query) {
        return """
            public %s(QueryExecutor executor) {
                this.executor = executor;
            }
            """
            .formatted(query.name());
    }
}
