package dev.sqlcj.generator;

import dev.sqlcj.analysis.QueryColumn;
import dev.sqlcj.analysis.QueryGroupModel;
import dev.sqlcj.analysis.QueryModel;
import dev.sqlcj.analysis.QueryParameter;
import dev.sqlcj.parser.QueryType;
import dev.sqlcj.schema.ColumnType;
import dev.sqlcj.type.DefaultTypeResolver;
import dev.sqlcj.type.TypeResolver;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

public final class JavaCodeGenerator implements CodeGenerator {

    private static final String DEFAULT_PACKAGE = "generated";

    private final TypeResolver typeResolver = new DefaultTypeResolver();
    private final String packageName;

    public JavaCodeGenerator() {
        this(DEFAULT_PACKAGE);
    }

    public JavaCodeGenerator(String packageName) {
        this.packageName = packageName;
    }

    /**
     * Generates one repository holding every method of the group, in query
     * order, with one executor field and one constructor.
     */
    @Override
    public GeneratedFile generate(QueryGroupModel group) {
        JavaNames names = JavaNames.of(group);

        return new GeneratedFile(
            buildPath(names),
            generateSource(group, names)
        );
    }

    private Path buildPath(JavaNames names) {
        return packageDirectory().resolve(names.repositoryClassName() + ".java");
    }

    private Path packageDirectory() {
        String[] segments = packageName.split("\\.");

        return Path.of(
            segments[0],
            Arrays.copyOfRange(segments, 1, segments.length)
        );
    }

    private String generateSource(QueryGroupModel group, JavaNames names) {
        return """
            %s

            %s

            %s

            %s
            """
            .formatted(
                generatePackage(),
                generateImports(group),
                generateRepositoryJavaDoc(group).stripTrailing(),
                generateClass(group, names)
            );
    }

    private String generatePackage() {
        return "package " + packageName + ";";
    }

    private String generateImports(QueryGroupModel group) {
        Set<String> imports = new LinkedHashSet<>();

        imports.add("dev.sqlcj.runtime.QueryExecutor");

        if (group.queries().stream().anyMatch(this::hasResult)) {
            imports.add("dev.sqlcj.runtime.RowMapper");
        }

        if (group.queries().stream().anyMatch(query -> hasResult(query) || isExec(query))) {
            imports.add("java.util.List");
        }

        for (QueryModel query : group.queries()) {
            query.columns().stream()
                .map(QueryColumn::type)
                .map(this::resolveImport)
                .filter(Objects::nonNull)
                .forEach(imports::add);

            query.parameters().stream()
                .map(QueryParameter::type)
                .map(this::resolveImport)
                .filter(Objects::nonNull)
                .forEach(imports::add);
        }

        return imports.stream()
            .map(type -> "import " + type + ";")
            .collect(Collectors.joining("\n"));
    }

    private boolean hasResult(QueryModel query) {
        return query.type() == QueryType.ONE
            || query.type() == QueryType.MANY;
    }

    private boolean isExec(QueryModel query) {
        return query.type() == QueryType.EXEC;
    }

    /** A write query has no generated result record. */
    private boolean hasResultType(QueryModel query) {
        return !isExec(query);
    }

    /**
     * A query that returns one complete table row uses the repository's shared
     * row record and row mapper instead of generating its own.
     */
    private boolean returnsSharedRow(QueryModel query) {
        return query.rowTable() != null;
    }

    private String resolveImport(ColumnType type) {
        return switch (type) {
            case DATE -> "java.time.LocalDate";
            case TIMESTAMP -> "java.time.LocalDateTime";
            case TIMESTAMP_WITH_TIME_ZONE -> "java.time.OffsetDateTime";
            case DECIMAL -> "java.math.BigDecimal";
            case UUID -> "java.util.UUID";
            default -> null;
        };
    }

    private String generateRepositoryJavaDoc(QueryGroupModel group) {
        return """
            /**
             * Generated by sqlcj.
             *
             * Repository: %s
             */
            """
            .formatted(escapeJavadoc(group.name()));
    }

    private String generateJavaDoc(QueryModel query) {
        return """
            /**
             * Query: %s
             * Table: %s
             * Type: %s
             */
            """
            .formatted(
                escapeJavadoc(query.name()),
                escapeJavadoc(query.table()),
                query.type()
            );
    }

    private String generateClass(QueryGroupModel group, JavaNames names) {
        List<String> members = new ArrayList<>();

        members.add(generateExecutorField());
        members.add(generateConstructor(names));

        for (JavaNames.RowNames row : names.rows()) {
            List<QueryColumn> columns = group.queries().get(row.queryIndex()).columns();

            members.add(generateRecord(row.typeName(), columns, row.componentNames()));
            members.add(generateRowMapper(row.typeName(), row.mapperName(), columns));
        }

        for (int index = 0; index < group.queries().size(); index++) {
            QueryModel query = group.queries().get(index);
            JavaNames.QueryNames queryNames = names.queries().get(index);

            if (hasResultType(query) && !returnsSharedRow(query)) {
                members.add(
                    generateRecord(
                        queryNames.resultTypeName(),
                        query.columns(),
                        queryNames.componentNames()
                    )
                );
            }

            if (hasResult(query) && !returnsSharedRow(query)) {
                members.add(
                    generateRowMapper(
                        queryNames.resultTypeName(),
                        queryNames.rowMapperName(),
                        query.columns()
                    )
                );
            }

            members.add(generateJavaDoc(query) + generateMethod(query, queryNames));
        }

        return """
            public final class %s {

            %s
            }
            """
            .formatted(
                names.repositoryClassName(),
                members.stream()
                    .filter(member -> !member.isBlank())
                    .map(this::indent)
                    .collect(Collectors.joining("\n\n"))
            );
    }

    private String indent(String text) {
        return text.indent(4).stripTrailing();
    }

    /** Generates one nested result or row record in selected-column order. */
    private String generateRecord(
        String typeName,
        List<QueryColumn> columns,
        List<String> componentNames
    ) {
        return """
            public record %s(
            %s
            ) {
            }
            """
            .formatted(
                typeName,
                generateResultComponents(columns, componentNames)
            );
    }

    private String generateResultComponents(List<QueryColumn> columns, List<String> componentNames) {
        return IntStream.range(0, columns.size())
            .mapToObj(
                index -> generateResultComponent(
                    columns.get(index),
                    componentNames.get(index)
                )
            )
            .collect(Collectors.joining(",\n"));
    }

    private String generateResultComponent(QueryColumn column, String name) {
        return "%s %s"
            .formatted(
                typeResolver.resolve(column.type()),
                name
            )
            .indent(4)
            .stripTrailing();
    }

    private String generateMethodParameters(QueryModel query, JavaNames.QueryNames names) {
        return IntStream.range(0, query.parameters().size())
            .mapToObj(index -> {
                QueryParameter parameter = query.parameters().get(index);

                return typeResolver.resolve(parameter.type())
                    + " "
                    + names.parameterNames().get(index);
            })
            .collect(Collectors.joining(", "));
    }

    private String generateMethod(QueryModel query, JavaNames.QueryNames names) {
        return switch (query.type()) {
            case ONE, MANY -> generateQueryMethod(query, names);
            case EXEC -> generateExecMethod(query, names);
            case EXEC_RESULT, BATCH_EXEC, BATCH_MANY, BATCH_ONE -> generateUnsupportedMethod(query, names);
        };
    }

    private String generateQueryMethod(QueryModel query, JavaNames.QueryNames names) {
        return """
            public %s %s(%s) {
                return executor.%s(
                        %s,
                        %s,
                        %s
                );
            }
            """
            .formatted(
                generateReturnType(query, names),
                names.methodName(),
                generateMethodParameters(query, names),
                generateExecutorMethod(query),
                generateSql(query),
                generateParameterList(query, names),
                names.rowMapperName()
            );
    }

    private String generateExecMethod(QueryModel query, JavaNames.QueryNames names) {
        return """
            public %s %s(%s) {
                return executor.execute(
                        %s,
                        %s
                );
            }
            """
            .formatted(
                generateReturnType(query, names),
                names.methodName(),
                generateMethodParameters(query, names),
                generateSql(query),
                generateParameterList(query, names)
            );
    }

    private String generateUnsupportedMethod(QueryModel query, JavaNames.QueryNames names) {
        return """
            public %s %s(%s) {
                throw new UnsupportedOperationException("Not implemented");
            }
            """
            .formatted(
                generateReturnType(query, names),
                names.methodName(),
                generateMethodParameters(query, names)
            );
    }

    private String generateExecutorMethod(QueryModel query) {
        return switch (query.type()) {
            case ONE -> "query";
            case MANY -> "queryMany";
            default -> throw new IllegalStateException(
                "Query type does not produce a result: " + query.type()
            );
        };
    }

    private String generateSql(QueryModel query) {
        return "\"\"\"\n"
            + escapeTextBlock(query.executableSql())
            + "\"\"\"";
    }

    /**
     * Escapes the executable SQL rendered inside the generated text block so
     * that the compiled string is exactly the analyzed SQL, including
     * backslashes, embedded text-block delimiters, and line-trailing
     * whitespace.
     */
    private String escapeTextBlock(String sql) {
        StringBuilder builder = new StringBuilder();
        int quotes = 0;

        for (int index = 0; index < sql.length(); index++) {
            char character = sql.charAt(index);
            boolean lineEnd = isLineEnd(sql, index);

            if (character == '"') {
                quotes++;

                if (quotes == 3 || index + 1 == sql.length()) {
                    builder.append("\\\"");
                    quotes = 0;
                    continue;
                }

                builder.append('"');
                continue;
            }

            quotes = 0;

            switch (character) {
                case '\\' -> builder.append("\\\\");
                case '\r' -> builder.append("\\r");
                case ' ' -> builder.append(lineEnd ? "\\s" : " ");
                case '\t' -> builder.append(lineEnd ? "\\t" : "\t");
                default -> builder.append(character);
            }
        }

        return builder.toString();
    }

    private boolean isLineEnd(String sql, int index) {
        if (index + 1 == sql.length()) {
            return true;
        }

        char next = sql.charAt(index + 1);

        return next == '\n' || next == '\r';
    }

    /**
     * Renders the executor arguments in the textual order of the JDBC
     * {@code ?} positions, using the logically ordered method parameter names.
     *
     * <p>The argument list is built with {@code java.util.Arrays.asList} rather
     * than {@code List.of} so that a null argument can be bound.
     */
    private String generateParameterList(QueryModel query, JavaNames.QueryNames names) {
        Map<Integer, String> namesByIndex = generateParameterNamesByIndex(query, names);

        return query.bindingParameterIndexes().stream()
            .map(namesByIndex::get)
            .collect(Collectors.joining(", ", "java.util.Arrays.asList(", ")"));
    }

    private Map<Integer, String> generateParameterNamesByIndex(
        QueryModel query,
        JavaNames.QueryNames names
    ) {
        Map<Integer, String> namesByIndex = new LinkedHashMap<>();

        for (int index = 0; index < query.parameters().size(); index++) {
            namesByIndex.put(
                query.parameters().get(index).index(),
                names.parameterNames().get(index)
            );
        }

        return namesByIndex;
    }

    private String generateReturnType(QueryModel query, JavaNames.QueryNames names) {
        return switch (query.type()) {
            case ONE -> names.resultTypeName();
            case MANY -> "List<" + names.resultTypeName() + ">";
            case EXEC -> "int";
            case EXEC_RESULT -> "void";
            case BATCH_EXEC -> "void";
            case BATCH_MANY -> "void";
            case BATCH_ONE -> "void";
        };
    }

    private String generateRowMapper(String typeName, String mapperName, List<QueryColumn> columns) {
        return """
            private static final RowMapper<%s> %s =
                    resultSet -> new %s(
            %s
            );
            """
            .formatted(
                typeName,
                mapperName,
                typeName,
                generateResultMappings(columns)
            );
    }

    /**
     * Reads each result column by its one-based projection position so that
     * identically named columns from different sources stay distinct.
     */
    private String generateResultMappings(List<QueryColumn> columns) {
        return IntStream.range(0, columns.size())
            .mapToObj(
                index -> generateResultMapping(
                    columns.get(index),
                    index + 1
                )
            )
            .collect(Collectors.joining(",\n"));
    }

    private String generateResultMapping(QueryColumn column, int position) {
        String javaType = typeResolver.resolve(column.type());

        return "resultSet.getObject(%d, %s.class)"
            .formatted(position, javaType)
            .indent(8)
            .stripTrailing();
    }

    private String generateExecutorField() {
        return """
            private final QueryExecutor executor;
            """;
    }

    private String generateConstructor(JavaNames names) {
        return """
            public %s(QueryExecutor executor) {
                this.executor = executor;
            }
            """
            .formatted(names.repositoryClassName());
    }

    /**
     * Escapes a SQL-derived value rendered inside the generated Javadoc block.
     */
    private String escapeJavadoc(String value) {
        return value
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("*/", "*&#47;");
    }
}
