package dev.sqlcj.generator;

import dev.sqlcj.analysis.QueryColumn;
import dev.sqlcj.analysis.QueryGroupModel;
import dev.sqlcj.analysis.QueryModel;
import dev.sqlcj.analysis.QueryParameter;
import dev.sqlcj.parser.QueryType;
import dev.sqlcj.schema.ColumnType;
import dev.sqlcj.schema.EnumType;
import dev.sqlcj.type.DefaultTypeResolver;
import dev.sqlcj.type.TypeResolver;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

public final class JavaCodeGenerator implements CodeGenerator {

    private static final String DEFAULT_PACKAGE = "generated";

    private static final String GENERATED_NOTICE = "// Code generated by sqlcj. DO NOT EDIT.";

    private final TypeResolver typeResolver = new DefaultTypeResolver();
    private final String packageName;

    /**
     * The row records of the package, keyed by row identity and ordered by the
     * group that first returned them.
     */
    private final Map<String, SharedRow> rows = new LinkedHashMap<>();

    /** The rows of the package, keyed by the lower-case row type name. */
    private final Map<String, SharedRow> rowsByPortabilityKey = new LinkedHashMap<>();

    /**
     * The enum types the package generates, keyed by enum identity and ordered
     * by the group that first used them.
     */
    private final Map<String, SharedEnum> enums = new LinkedHashMap<>();

    /** The enum types of the package, keyed by the lower-case enum type name. */
    private final Map<String, SharedEnum> enumsByPortabilityKey = new LinkedHashMap<>();

    /**
     * Every other type the package generates — repositories, row records, and
     * nested result records — keyed by its lower-case name, so that an enum
     * type cannot take a name one of them already generated.
     */
    private final Map<String, String> generatedTypesByPortabilityKey = new LinkedHashMap<>();

    public JavaCodeGenerator() {
        this(DEFAULT_PACKAGE);
    }

    public JavaCodeGenerator(String packageName) {
        this.packageName = packageName;
    }

    /**
     * Generates one repository holding every method of the group, in query
     * order, with one executor field and one constructor, and records the row
     * records the group returns.
     */
    @Override
    public GeneratedFile generate(QueryGroupModel group) {
        JavaNames names = JavaNames.of(group);

        recordRows(group, names);
        recordGeneratedTypes(group, names);
        recordEnums(group);

        return new GeneratedFile(
            buildPath(names),
            generateSource(group, names)
        );
    }

    @Override
    public List<GeneratedFile> generateRows() {
        return rows.values().stream()
            .map(this::generateRowFile)
            .toList();
    }

    @Override
    public List<GeneratedFile> generateEnums() {
        return enums.values().stream()
            .map(this::generateEnumFile)
            .toList();
    }

    /**
     * Records the row records of one group, rejecting a row that conflicts with
     * a row an earlier group of the package already generated.
     */
    private void recordRows(QueryGroupModel group, JavaNames names) {
        for (JavaNames.RowNames row : names.rows()) {
            recordRow(
                new SharedRow(
                    group.name(),
                    row.tableName(),
                    row.typeName(),
                    group.queries().get(row.queryIndex()).columns(),
                    row.componentNames()
                )
            );
        }
    }

    /**
     * Records one row record of the package. A row of a table already recorded
     * under the same row type is the same record, so its columns must be the
     * ones the earlier group defined; a row type equal ignoring case to the row
     * type of another table is rejected, because the compiled class files of
     * those types are one path on a case-insensitive filesystem.
     */
    private void recordRow(SharedRow row) {
        SharedRow recorded = rows.get(row.identity());

        if (recorded != null) {
            if (!recorded.columns().equals(row.columns())) {
                throw new IllegalArgumentException(
                    "Table '%s' differs from its definition in query group '%s', which generates the same row type %s"
                        .formatted(
                            row.tableName(),
                            recorded.groupName(),
                            row.typeName()
                        )
                );
            }

            return;
        }

        SharedRow previous = rowsByPortabilityKey.get(row.portabilityKey());

        if (previous != null) {
            throw new IllegalArgumentException(
                "Tables '%s' and '%s' generate row types that are equal ignoring case: %s and %s"
                    .formatted(
                        previous.tableName(),
                        row.tableName(),
                        previous.typeName(),
                        row.typeName()
                    )
            );
        }

        rows.put(row.identity(), row);
        rowsByPortabilityKey.put(row.portabilityKey(), row);
    }

    /**
     * One row record of the package, generated once from the group that first
     * returned it.
     */
    private record SharedRow(
        String groupName,
        String tableName,
        String typeName,
        List<QueryColumn> columns,
        List<String> componentNames
    ) {

        /**
         * Two rows are the same record when they generate the same row type for
         * the same table, compared as a case-insensitive filesystem compares
         * the table's generated file.
         */
        String identity() {
            return typeName + "\n" + tableName.toLowerCase(Locale.ROOT);
        }

        String portabilityKey() {
            return typeName.toLowerCase(Locale.ROOT);
        }
    }

    /**
     * Records the types one group generates beside its enums: its repository,
     * the row records it returns, and the nested result records of its other
     * queries.
     */
    private void recordGeneratedTypes(QueryGroupModel group, JavaNames names) {
        recordGeneratedType(names.repositoryClassName());

        for (JavaNames.RowNames row : names.rows()) {
            recordGeneratedType(row.typeName());
        }

        for (int index = 0; index < group.queries().size(); index++) {
            QueryModel query = group.queries().get(index);

            if (hasResultType(query) && !returnsSharedRow(query)) {
                recordGeneratedType(names.queries().get(index).resultTypeName());
            }
        }
    }

    /**
     * Records one generated type of the package, rejecting a type whose name is
     * equal ignoring case to an enum type an earlier group already generated,
     * because the compiled class files of those types are one path on a
     * case-insensitive filesystem.
     */
    private void recordGeneratedType(String typeName) {
        String portabilityKey = typeName.toLowerCase(Locale.ROOT);
        SharedEnum generatedEnum = enumsByPortabilityKey.get(portabilityKey);

        if (generatedEnum != null) {
            throw enumTypeCollision(generatedEnum, typeName);
        }

        generatedTypesByPortabilityKey.putIfAbsent(portabilityKey, typeName);
    }

    /**
     * Records the enum types one group uses, in the order its columns and
     * parameters first name them.
     */
    private void recordEnums(QueryGroupModel group) {
        for (QueryModel query : group.queries()) {
            for (QueryColumn column : query.columns()) {
                if (column.type() == ColumnType.ENUM) {
                    recordEnum(group, column.enumType());
                }
            }

            for (QueryParameter parameter : query.parameters()) {
                if (parameter.type() == ColumnType.ENUM) {
                    recordEnum(group, parameter.enumType());
                }
            }
        }
    }

    private void recordEnum(QueryGroupModel group, String enumName) {
        EnumType declared = group.enums().stream()
            .filter(candidate -> candidate.name().equalsIgnoreCase(enumName))
            .findFirst()
            .orElseThrow(
                () -> new IllegalStateException("Enum type not found in schema: " + enumName)
            );

        recordEnum(
            new SharedEnum(
                group.name(),
                declared.name(),
                JavaNames.enumTypeName(declared.name()),
                declared.labels(),
                JavaNames.enumConstantNames(declared.name(), declared.labels())
            )
        );
    }

    /**
     * Records one enum type of the package. An enum already recorded under the
     * same enum type is the same Java enum, so its labels must be the ones the
     * earlier group defined; an enum type equal ignoring case to another enum
     * or to another generated type is rejected, because the compiled class
     * files of those types are one path on a case-insensitive filesystem.
     */
    private void recordEnum(SharedEnum sharedEnum) {
        SharedEnum recorded = enums.get(sharedEnum.identity());

        if (recorded != null) {
            if (!recorded.labels().equals(sharedEnum.labels())) {
                throw new IllegalArgumentException(
                    "Enum type '%s' differs from its definition in query group '%s', which generates the same enum type %s"
                        .formatted(
                            sharedEnum.enumName(),
                            recorded.groupName(),
                            sharedEnum.typeName()
                        )
                );
            }

            return;
        }

        SharedEnum previous = enumsByPortabilityKey.get(sharedEnum.portabilityKey());

        if (previous != null) {
            throw new IllegalArgumentException(
                "Enum types '%s' and '%s' generate enum types that are equal ignoring case: %s and %s"
                    .formatted(
                        previous.enumName(),
                        sharedEnum.enumName(),
                        previous.typeName(),
                        sharedEnum.typeName()
                    )
            );
        }

        String generatedType = generatedTypesByPortabilityKey.get(sharedEnum.portabilityKey());

        if (generatedType != null) {
            throw enumTypeCollision(sharedEnum, generatedType);
        }

        enums.put(sharedEnum.identity(), sharedEnum);
        enumsByPortabilityKey.put(sharedEnum.portabilityKey(), sharedEnum);
    }

    private IllegalArgumentException enumTypeCollision(SharedEnum sharedEnum, String typeName) {
        return new IllegalArgumentException(
            "Enum type '%s' generates %s, which is equal ignoring case to the generated type %s"
                .formatted(
                    sharedEnum.enumName(),
                    sharedEnum.typeName(),
                    typeName
                )
        );
    }

    /**
     * One Java enum of the package, generated once from the group that first
     * used the enum type it is generated from.
     */
    private record SharedEnum(
        String groupName,
        String enumName,
        String typeName,
        List<String> labels,
        List<String> constantNames
    ) {

        /**
         * Two uses are the same Java enum when they generate the same enum type
         * from the same enum type name, compared as a case-insensitive
         * filesystem compares the type's generated file.
         */
        String identity() {
            return typeName + "\n" + enumName.toLowerCase(Locale.ROOT);
        }

        String portabilityKey() {
            return typeName.toLowerCase(Locale.ROOT);
        }
    }

    private Path buildPath(JavaNames names) {
        return packageDirectory().resolve(names.repositoryClassName() + ".java");
    }

    private Path packageDirectory() {
        String[] segments = packageName.split("\\.");

        return Path.of(
            segments[0],
            Arrays.copyOfRange(segments, 1, segments.length)
        );
    }

    private String generateSource(QueryGroupModel group, JavaNames names) {
        return """
            %s

            %s

            %s

            %s

            %s
            """
            .formatted(
                GENERATED_NOTICE,
                generatePackage(),
                generateImports(group),
                generateRepositoryJavaDoc(group).stripTrailing(),
                generateClass(group, names)
            );
    }

    /** Generates the file of one row record of the package. */
    private GeneratedFile generateRowFile(SharedRow row) {
        return new GeneratedFile(
            packageDirectory().resolve(row.typeName() + ".java"),
            generateRowSource(row)
        );
    }

    private String generateRowSource(SharedRow row) {
        List<String> sections = new ArrayList<>();

        sections.add(GENERATED_NOTICE);
        sections.add(generatePackage());

        String imports = generateRowImports(row);

        if (!imports.isEmpty()) {
            sections.add(imports);
        }

        sections.add(generateRowJavaDoc(row).stripTrailing());

        sections.add(
            generateRecord(
                row.typeName(),
                row.columns(),
                row.componentNames()
            )
        );

        return String.join("\n\n", sections);
    }

    /** Generates the file of one Java enum of the package. */
    private GeneratedFile generateEnumFile(SharedEnum sharedEnum) {
        return new GeneratedFile(
            packageDirectory().resolve(sharedEnum.typeName() + ".java"),
            generateEnumSource(sharedEnum)
        );
    }

    private String generateEnumSource(SharedEnum sharedEnum) {
        return String.join(
            "\n\n",
            GENERATED_NOTICE,
            generatePackage(),
            generateEnumJavaDoc(sharedEnum).stripTrailing(),
            generateEnum(sharedEnum)
        );
    }

    private String generateEnumJavaDoc(SharedEnum sharedEnum) {
        return """
            /**
             * Generated by sqlcj.
             *
             * Enum: %s
             */
            """
            .formatted(escapeJavadoc(sharedEnum.enumName()));
    }

    /**
     * Generates one Java enum, holding one constant per label in label order,
     * each carrying the label PostgreSQL stores. The constant list ends with
     * {@code ;} even when the enum type declares no label, so the generated
     * source compiles either way.
     */
    private String generateEnum(SharedEnum sharedEnum) {
        List<String> members = List.of(
            generateEnumConstants(sharedEnum),
            "private final String label;",
            generateEnumConstructor(sharedEnum),
            generateEnumLabelMethod(),
            generateFromLabelMethod(sharedEnum)
        );

        return """
            public enum %s {

            %s
            }
            """
            .formatted(
                sharedEnum.typeName(),
                members.stream()
                    .map(this::indentEnumMember)
                    .collect(Collectors.joining("\n\n"))
            );
    }

    private String generateEnumConstants(SharedEnum sharedEnum) {
        return IntStream.range(0, sharedEnum.labels().size())
            .mapToObj(
                index -> sharedEnum.constantNames().get(index)
                    + "("
                    + generateStringLiteral(sharedEnum.labels().get(index))
                    + ")"
            )
            .collect(Collectors.joining(",\n"))
            + ";";
    }

    private String generateEnumConstructor(SharedEnum sharedEnum) {
        return """
            %s(String label) {
                this.label = label;
            }
            """
            .formatted(sharedEnum.typeName());
    }

    private String generateEnumLabelMethod() {
        return """
            public String label() {
                return label;
            }
            """;
    }

    /**
     * Generates the reverse lookup a generated read uses: {@code null} for a
     * SQL {@code NULL}, and a failure for a label the generated enum does not
     * hold, which means the database has a label the schema source does not
     * declare.
     */
    private String generateFromLabelMethod(SharedEnum sharedEnum) {
        return """
            public static %s fromLabel(String label) {
                if (label == null) {
                    return null;
                }

                for (%s value : values()) {
                    if (value.label.equals(label)) {
                        return value;
                    }
                }

                throw new IllegalArgumentException(%s + label);
            }
            """
            .formatted(
                sharedEnum.typeName(),
                sharedEnum.typeName(),
                generateStringLiteral(
                    "Unknown label for enum type " + sharedEnum.enumName() + ": "
                )
            );
    }

    /**
     * A row record depends on the JDK types of its components alone, which for
     * an array component are {@code java.util.List} and the JDK type of its
     * elements, in the order the components name them.
     */
    private String generateRowImports(SharedRow row) {
        Set<String> imports = new LinkedHashSet<>();

        for (QueryColumn column : row.columns()) {
            if (column.array()) {
                imports.add("java.util.List");
            }

            String elementImport = resolveImport(column.type());

            if (elementImport != null) {
                imports.add(elementImport);
            }
        }

        return imports.stream()
            .map(type -> "import " + type + ";")
            .collect(Collectors.joining("\n"));
    }

    private String generateRowJavaDoc(SharedRow row) {
        return """
            /**
             * Generated by sqlcj.
             *
             * Table: %s
             */
            """
            .formatted(escapeJavadoc(row.tableName()));
    }

    private String generatePackage() {
        return "package " + packageName + ";";
    }

    private String generateImports(QueryGroupModel group) {
        Set<String> imports = new LinkedHashSet<>();

        imports.add("dev.sqlcj.runtime.QueryExecutor");

        if (group.queries().stream().anyMatch(this::hasResult)) {
            imports.add("dev.sqlcj.runtime.RowMapper");
        }

        if (group.queries().stream().anyMatch(query -> hasResult(query) || isExec(query))) {
            imports.add("java.util.List");
        }

        if (group.queries().stream().anyMatch(this::isOptional)) {
            imports.add("java.util.Optional");
        }

        for (QueryModel query : group.queries()) {
            query.columns().stream()
                .map(QueryColumn::type)
                .map(this::resolveImport)
                .filter(Objects::nonNull)
                .forEach(imports::add);

            query.parameters().stream()
                .map(QueryParameter::type)
                .map(this::resolveImport)
                .filter(Objects::nonNull)
                .forEach(imports::add);
        }

        return imports.stream()
            .map(type -> "import " + type + ";")
            .collect(Collectors.joining("\n"));
    }

    private boolean hasResult(QueryModel query) {
        return query.type() == QueryType.ONE
            || query.type() == QueryType.OPTIONAL
            || query.type() == QueryType.MANY;
    }

    private boolean isOptional(QueryModel query) {
        return query.type() == QueryType.OPTIONAL;
    }

    private boolean isExec(QueryModel query) {
        return query.type() == QueryType.EXEC;
    }

    /** A write query has no generated result record. */
    private boolean hasResultType(QueryModel query) {
        return !isExec(query);
    }

    /**
     * A query that returns one complete table row uses the package's row record
     * and the repository's row mapper instead of generating its own.
     */
    private boolean returnsSharedRow(QueryModel query) {
        return query.rowTable() != null;
    }

    private String resolveImport(ColumnType type) {
        return switch (type) {
            case DATE -> "java.time.LocalDate";
            case TIME -> "java.time.LocalTime";
            case TIMESTAMP -> "java.time.LocalDateTime";
            case TIMESTAMP_WITH_TIME_ZONE -> "java.time.OffsetDateTime";
            case DECIMAL -> "java.math.BigDecimal";
            case UUID -> "java.util.UUID";
            default -> null;
        };
    }

    private String generateRepositoryJavaDoc(QueryGroupModel group) {
        return """
            /**
             * Generated by sqlcj.
             *
             * Repository: %s
             */
            """
            .formatted(escapeJavadoc(group.name()));
    }

    private String generateJavaDoc(QueryModel query) {
        return """
            /**
             * Query: %s
             * Table: %s
             * Type: %s
             */
            """
            .formatted(
                escapeJavadoc(query.name()),
                escapeJavadoc(query.table()),
                query.type()
            );
    }

    private String generateClass(QueryGroupModel group, JavaNames names) {
        List<String> members = new ArrayList<>();

        members.add(generateExecutorField());
        members.add(generateConstructor(names));

        for (JavaNames.RowNames row : names.rows()) {
            members.add(
                generateRowMapper(
                    row.typeName(),
                    row.mapperName(),
                    group.queries().get(row.queryIndex()).columns()
                )
            );
        }

        for (int index = 0; index < group.queries().size(); index++) {
            QueryModel query = group.queries().get(index);
            JavaNames.QueryNames queryNames = names.queries().get(index);

            if (hasResultType(query) && !returnsSharedRow(query)) {
                members.add(
                    generateRecord(
                        queryNames.resultTypeName(),
                        query.columns(),
                        queryNames.componentNames()
                    )
                );
            }

            if (hasResult(query) && !returnsSharedRow(query)) {
                members.add(
                    generateRowMapper(
                        queryNames.resultTypeName(),
                        queryNames.rowMapperName(),
                        query.columns()
                    )
                );
            }

            members.add(
                generateJavaDoc(query)
                    + generateMethod(query, names.repositoryClassName(), queryNames)
            );
        }

        return """
            public final class %s {

            %s
            }
            """
            .formatted(
                names.repositoryClassName(),
                members.stream()
                    .filter(member -> !member.isBlank())
                    .map(this::indent)
                    .collect(Collectors.joining("\n\n"))
            );
    }

    private String indent(String text) {
        return text.indent(4).stripTrailing();
    }

    /**
     * Indents one member of a generated enum, leaving a blank line inside it
     * blank rather than indented, so the generated enum carries no trailing
     * whitespace. Only these members are written with blank lines inside them.
     */
    private String indentEnumMember(String text) {
        return indent(text)
            .lines()
            .map(String::stripTrailing)
            .collect(Collectors.joining("\n"));
    }

    /** Generates one result or row record in selected-column order. */
    private String generateRecord(
        String typeName,
        List<QueryColumn> columns,
        List<String> componentNames
    ) {
        return """
            public record %s(
            %s
            ) {
            }
            """
            .formatted(
                typeName,
                generateResultComponents(columns, componentNames)
            );
    }

    private String generateResultComponents(List<QueryColumn> columns, List<String> componentNames) {
        return IntStream.range(0, columns.size())
            .mapToObj(
                index -> generateResultComponent(
                    columns.get(index),
                    componentNames.get(index)
                )
            )
            .collect(Collectors.joining(",\n"));
    }

    private String generateResultComponent(QueryColumn column, String name) {
        return "%s %s"
            .formatted(
                javaType(column.type(), column.enumType(), column.array()),
                name
            )
            .indent(4)
            .stripTrailing();
    }

    /**
     * The Java type of one column or parameter, which is the generated enum of
     * its enum type for an enum and the mapped type of its column type
     * otherwise. A generated enum belongs to the generated package, so it is
     * referenced by its simple name and needs no import. An array column or
     * parameter is a {@code List} of that type.
     */
    private String javaType(ColumnType type, String enumType, boolean array) {
        String elementType = type == ColumnType.ENUM
            ? JavaNames.enumTypeName(enumType)
            : typeResolver.resolve(type);

        return array
            ? "List<" + elementType + ">"
            : elementType;
    }

    private String generateMethodParameters(QueryModel query, JavaNames.QueryNames names) {
        return IntStream.range(0, query.parameters().size())
            .mapToObj(index -> {
                QueryParameter parameter = query.parameters().get(index);

                return javaType(parameter.type(), parameter.enumType(), parameter.array())
                    + " "
                    + names.parameterNames().get(index);
            })
            .collect(Collectors.joining(", "));
    }

    private String generateMethod(
        QueryModel query,
        String repositoryClassName,
        JavaNames.QueryNames names
    ) {
        return switch (query.type()) {
            case ONE, OPTIONAL, MANY -> generateQueryMethod(query, repositoryClassName, names);
            case EXEC -> generateExecMethod(query, repositoryClassName, names);
            case EXEC_RESULT, BATCH_EXEC, BATCH_MANY, BATCH_ONE -> generateUnsupportedMethod(query, names);
        };
    }

    private String generateQueryMethod(
        QueryModel query,
        String repositoryClassName,
        JavaNames.QueryNames names
    ) {
        return """
            public %s %s(%s) {
                return executor.%s(
                        %s,
                        %s,
                        %s,
                        %s,
                        %s
                );
            }
            """
            .formatted(
                generateReturnType(query, names),
                names.methodName(),
                generateMethodParameters(query, names),
                generateExecutorMethod(query),
                generateStringLiteral(repositoryClassName),
                generateStringLiteral(query.name()),
                generateSql(query),
                generateParameterList(query, names),
                names.rowMapperName()
            );
    }

    private String generateExecMethod(
        QueryModel query,
        String repositoryClassName,
        JavaNames.QueryNames names
    ) {
        return """
            public %s %s(%s) {
                return executor.execute(
                        %s,
                        %s,
                        %s,
                        %s
                );
            }
            """
            .formatted(
                generateReturnType(query, names),
                names.methodName(),
                generateMethodParameters(query, names),
                generateStringLiteral(repositoryClassName),
                generateStringLiteral(query.name()),
                generateSql(query),
                generateParameterList(query, names)
            );
    }

    private String generateUnsupportedMethod(QueryModel query, JavaNames.QueryNames names) {
        return """
            public %s %s(%s) {
                throw new UnsupportedOperationException("Not implemented");
            }
            """
            .formatted(
                generateReturnType(query, names),
                names.methodName(),
                generateMethodParameters(query, names)
            );
    }

    private String generateExecutorMethod(QueryModel query) {
        return switch (query.type()) {
            case ONE -> "queryOne";
            case OPTIONAL -> "queryOptional";
            case MANY -> "queryMany";
            default -> throw new IllegalStateException(
                "Query type does not produce a result: " + query.type()
            );
        };
    }

    /**
     * Renders the repository and query identity an executor call reports in its
     * failures as a Java string literal.
     */
    private String generateStringLiteral(String value) {
        return "\""
            + value
                .replace("\\", "\\\\")
                .replace("\"", "\\\"")
            + "\"";
    }

    private String generateSql(QueryModel query) {
        return "\"\"\"\n"
            + escapeTextBlock(query.executableSql())
            + "\"\"\"";
    }

    /**
     * Escapes the executable SQL rendered inside the generated text block so
     * that the compiled string is exactly the analyzed SQL, including
     * backslashes, embedded text-block delimiters, and line-trailing
     * whitespace.
     */
    private String escapeTextBlock(String sql) {
        StringBuilder builder = new StringBuilder();
        int quotes = 0;

        for (int index = 0; index < sql.length(); index++) {
            char character = sql.charAt(index);
            boolean lineEnd = isLineEnd(sql, index);

            if (character == '"') {
                quotes++;

                if (quotes == 3 || index + 1 == sql.length()) {
                    builder.append("\\\"");
                    quotes = 0;
                    continue;
                }

                builder.append('"');
                continue;
            }

            quotes = 0;

            switch (character) {
                case '\\' -> builder.append("\\\\");
                case '\r' -> builder.append("\\r");
                case ' ' -> builder.append(lineEnd ? "\\s" : " ");
                case '\t' -> builder.append(lineEnd ? "\\t" : "\t");
                default -> builder.append(character);
            }
        }

        return builder.toString();
    }

    private boolean isLineEnd(String sql, int index) {
        if (index + 1 == sql.length()) {
            return true;
        }

        char next = sql.charAt(index + 1);

        return next == '\n' || next == '\r';
    }

    /**
     * Renders the executor arguments in the textual order of the JDBC
     * {@code ?} positions, using the logically ordered method parameter names.
     *
     * <p>The argument list is built with {@code java.util.Arrays.asList} rather
     * than {@code List.of} so that a null argument can be bound.
     */
    private String generateParameterList(QueryModel query, JavaNames.QueryNames names) {
        Map<Integer, String> argumentsByIndex = generateArgumentsByIndex(query, names);

        return query.bindingParameterIndexes().stream()
            .map(argumentsByIndex::get)
            .collect(Collectors.joining(", ", "java.util.Arrays.asList(", ")"));
    }

    /**
     * Renders the executor argument of each logical parameter, keyed by the
     * placeholder index it is bound at, so that a repeated index renders the
     * same argument at each of its binding positions.
     */
    private Map<Integer, String> generateArgumentsByIndex(
        QueryModel query,
        JavaNames.QueryNames names
    ) {
        Map<Integer, String> argumentsByIndex = new LinkedHashMap<>();

        for (int index = 0; index < query.parameters().size(); index++) {
            QueryParameter parameter = query.parameters().get(index);

            argumentsByIndex.put(
                parameter.index(),
                generateArgument(parameter, names.parameterNames().get(index))
            );
        }

        return argumentsByIndex;
    }

    /**
     * Renders one executor argument. A JSON parameter is wrapped in
     * {@code dev.sqlcj.runtime.UntypedText} so that the runtime binds its text
     * without a declared SQL type and the database types it from the context of
     * its placeholder. An enum parameter is wrapped the same way, around the
     * label of the generated constant, because PostgreSQL rejects a label bound
     * as {@code varchar} where an enum is expected. An array parameter is
     * wrapped in {@code dev.sqlcj.runtime.SqlArray} with the element type's
     * PostgreSQL name, so that the runtime binds the list as a server array.
     * Every wrapper is written out in full, so the generated imports are the
     * same as without it.
     */
    private String generateArgument(QueryParameter parameter, String name) {
        if (parameter.array()) {
            return generateArrayArgument(parameter, name);
        }

        if (parameter.type() == ColumnType.ENUM) {
            return "new dev.sqlcj.runtime.UntypedText(%s == null ? null : %s.label())"
                .formatted(name, name);
        }

        if (isUntypedText(parameter.type())) {
            return "new dev.sqlcj.runtime.UntypedText(" + name + ")";
        }

        return name;
    }

    /**
     * Renders one array executor argument, which carries the element type's
     * PostgreSQL name beside the list. An array of an enum carries the labels
     * of its constants instead of the constants themselves, because the runtime
     * binds the values the database stores.
     */
    private String generateArrayArgument(QueryParameter parameter, String name) {
        if (parameter.type() == ColumnType.ENUM) {
            return "dev.sqlcj.runtime.SqlArray.of(%s, %s, %s::label)"
                .formatted(
                    generateStringLiteral(parameter.enumType()),
                    name,
                    JavaNames.enumTypeName(parameter.enumType())
                );
        }

        return "new dev.sqlcj.runtime.SqlArray(%s, %s)"
            .formatted(
                generateStringLiteral(elementTypeName(parameter)),
                name
            );
    }

    /**
     * The PostgreSQL name of one array element type, which is the name
     * {@code Connection.createArrayOf} resolves the array type from. Only the
     * element types sqlcj maps an array of have one. A blank-padded character
     * element is named {@code bpchar} rather than {@code varchar}, because
     * PostgreSQL compares a {@code bpchar} array only with another one.
     */
    private String elementTypeName(QueryParameter parameter) {
        if (parameter.blankPadded() && parameter.type() == ColumnType.VARCHAR) {
            return "bpchar";
        }

        return switch (parameter.type()) {
            case INTEGER -> "int4";
            case BIGINT -> "int8";
            case SMALLINT -> "int2";
            case BOOLEAN -> "bool";
            case VARCHAR -> "varchar";
            case TEXT -> "text";
            case DATE -> "date";
            case TIME -> "time";
            case TIMESTAMP -> "timestamp";
            case TIMESTAMP_WITH_TIME_ZONE -> "timestamptz";
            case DECIMAL -> "numeric";
            case REAL -> "float4";
            case DOUBLE_PRECISION -> "float8";
            case UUID -> "uuid";
            default -> throw new IllegalStateException(
                "Column type has no array element type: " + parameter.type()
            );
        };
    }

    /**
     * Reports whether a type's Java text is bound and read as text the database
     * types itself rather than through the JDBC type of {@code String}.
     */
    private boolean isUntypedText(ColumnType type) {
        return type == ColumnType.JSON || type == ColumnType.JSONB;
    }

    private String generateReturnType(QueryModel query, JavaNames.QueryNames names) {
        return switch (query.type()) {
            case ONE -> names.resultTypeName();
            case OPTIONAL -> "Optional<" + names.resultTypeName() + ">";
            case MANY -> "List<" + names.resultTypeName() + ">";
            case EXEC -> "int";
            case EXEC_RESULT -> "void";
            case BATCH_EXEC -> "void";
            case BATCH_MANY -> "void";
            case BATCH_ONE -> "void";
        };
    }

    private String generateRowMapper(String typeName, String mapperName, List<QueryColumn> columns) {
        return """
            private static final RowMapper<%s> %s =
                    resultSet -> new %s(
            %s
            );
            """
            .formatted(
                typeName,
                mapperName,
                typeName,
                generateResultMappings(columns)
            );
    }

    /**
     * Reads each result column by its one-based projection position so that
     * identically named columns from different sources stay distinct.
     */
    private String generateResultMappings(List<QueryColumn> columns) {
        return IntStream.range(0, columns.size())
            .mapToObj(
                index -> generateResultMapping(
                    columns.get(index),
                    index + 1
                )
            )
            .collect(Collectors.joining(",\n"));
    }

    /**
     * A JSON column is read with {@code getString}, because a driver reports it
     * as a type of its own for which {@code getObject(position, String.class)}
     * is not defined. An enum column reads its label the same way and resolves
     * it to the generated constant; an array column reads its elements through
     * {@code dev.sqlcj.runtime.SqlArray}, which reads each element as a scalar
     * of the element type is read; every other column is read as its mapped
     * Java type.
     */
    private String generateResultMapping(QueryColumn column, int position) {
        if (column.array()) {
            return generateArrayMapping(column, position)
                .indent(8)
                .stripTrailing();
        }

        if (column.type() == ColumnType.ENUM) {
            return "%s.fromLabel(resultSet.getString(%d))"
                .formatted(JavaNames.enumTypeName(column.enumType()), position)
                .indent(8)
                .stripTrailing();
        }

        if (isUntypedText(column.type())) {
            return "resultSet.getString(%d)"
                .formatted(position)
                .indent(8)
                .stripTrailing();
        }

        String javaType = typeResolver.resolve(column.type());

        return "resultSet.getObject(%d, %s.class)"
            .formatted(position, javaType)
            .indent(8)
            .stripTrailing();
    }

    /**
     * Reads one array column as a list of its element type. An array of an enum
     * reads each label and resolves it to the generated constant.
     */
    private String generateArrayMapping(QueryColumn column, int position) {
        if (column.type() == ColumnType.ENUM) {
            return "dev.sqlcj.runtime.SqlArray.getList(resultSet, %d, String.class, %s::fromLabel)"
                .formatted(position, JavaNames.enumTypeName(column.enumType()));
        }

        return "dev.sqlcj.runtime.SqlArray.getList(resultSet, %d, %s.class)"
            .formatted(position, typeResolver.resolve(column.type()));
    }

    private String generateExecutorField() {
        return """
            private final QueryExecutor executor;
            """;
    }

    private String generateConstructor(JavaNames names) {
        return """
            public %s(QueryExecutor executor) {
                this.executor = executor;
            }
            """
            .formatted(names.repositoryClassName());
    }

    /**
     * Escapes a SQL-derived value rendered inside the generated Javadoc block.
     */
    private String escapeJavadoc(String value) {
        return value
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("*/", "*&#47;");
    }
}
